environment: development

http:
  host: 0.0.0.0
  port: 8000

clients:
  identity: "http://0.0.0.0:4006"
  workspace: "http://0.0.0.0:4001"
  post: "http://0.0.0.0:4003"
  media: "http://0.0.0.0:4007"
