environment: production

http:
  host: 0.0.0.0
  port: 3000

clients:
  identity: "http://identity-service.default.svc.cluster.local"
  workspace: "http://workspace-service.default.svc.cluster.local"
  post: "http://post-service.default.svc.cluster.local"
  media: "http://media-service.default.svc.cluster.local"
