# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from media_sdk.models.media_status import MediaStatus

class TestMediaStatus(unittest.TestCase):
    """MediaStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMediaStatus(self):
        """Test MediaStatus"""
        # inst = MediaStatus()

if __name__ == '__main__':
    unittest.main()
