# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from media_sdk.models.get_media_batch_request import GetMediaBatchRequest

class TestGetMediaBatchRequest(unittest.TestCase):
    """GetMediaBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMediaBatchRequest:
        """Test GetMediaBatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMediaBatchRequest`
        """
        model = GetMediaBatchRequest()
        if include_optional:
            return GetMediaBatchRequest(
                media_ids = [
                    ''
                    ]
            )
        else:
            return GetMediaBatchRequest(
                media_ids = [
                    ''
                    ],
        )
        """

    def testGetMediaBatchRequest(self):
        """Test GetMediaBatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
