# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from media_sdk.api.media_api import MediaApi


class TestMediaApi(unittest.TestCase):
    """MediaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MediaApi()

    def tearDown(self) -> None:
        pass

    def test_delete_media(self) -> None:
        """Test case for delete_media

        Delete Media
        """
        pass

    def test_get_media_batch(self) -> None:
        """Test case for get_media_batch

        Get Media Batch
        """
        pass

    def test_get_media_by_id(self) -> None:
        """Test case for get_media_by_id

        Get Media By Id
        """
        pass

    def test_get_signed_url(self) -> None:
        """Test case for get_signed_url

        Get Signed Url
        """
        pass

    def test_list_media(self) -> None:
        """Test case for list_media

        List Media
        """
        pass

    def test_process(self) -> None:
        """Test case for process

        Process
        """
        pass


if __name__ == '__main__':
    unittest.main()
