# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from media_sdk.models.media_filters import MediaFilters

class TestMediaFilters(unittest.TestCase):
    """MediaFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MediaFilters:
        """Test MediaFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MediaFilters`
        """
        model = MediaFilters()
        if include_optional:
            return MediaFilters(
                status = 'pending',
                owner_service = '',
                owner_id = '',
                category = 'avatar'
            )
        else:
            return MediaFilters(
        )
        """

    def testMediaFilters(self):
        """Test MediaFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
