# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.flow_step import FlowStep

class TestFlowStep(unittest.TestCase):
    """FlowStep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFlowStep(self):
        """Test FlowStep"""
        # inst = FlowStep()

if __name__ == '__main__':
    unittest.main()
