# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.create_identifier_request import CreateIdentifierRequest

class TestCreateIdentifierRequest(unittest.TestCase):
    """CreateIdentifierRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateIdentifierRequest:
        """Test CreateIdentifierRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateIdentifierRequest`
        """
        model = CreateIdentifierRequest()
        if include_optional:
            return CreateIdentifierRequest(
                user_id = '',
                value = ''
            )
        else:
            return CreateIdentifierRequest(
                user_id = '',
                value = '',
        )
        """

    def testCreateIdentifierRequest(self):
        """Test CreateIdentifierRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
