# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_activate_user(self) -> None:
        """Test case for activate_user

        Activate User
        """
        pass

    def test_create_user(self) -> None:
        """Test case for create_user

        Create User
        """
        pass

    def test_delete_user(self) -> None:
        """Test case for delete_user

        Delete User
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Get User By Id
        """
        pass

    def test_get_users_batch(self) -> None:
        """Test case for get_users_batch

        Get Users Batch
        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        List Users
        """
        pass

    def test_suspend_user(self) -> None:
        """Test case for suspend_user

        Suspend User
        """
        pass

    def test_update_user(self) -> None:
        """Test case for update_user

        Update User
        """
        pass


if __name__ == '__main__':
    unittest.main()
