# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.api.identifiers_api import IdentifiersApi


class TestIdentifiersApi(unittest.TestCase):
    """IdentifiersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IdentifiersApi()

    def tearDown(self) -> None:
        pass

    def test_create_identifier(self) -> None:
        """Test case for create_identifier

        Create Identifier
        """
        pass

    def test_delete_identifier(self) -> None:
        """Test case for delete_identifier

        Delete Identifier
        """
        pass

    def test_set_default_identifier(self) -> None:
        """Test case for set_default_identifier

        Set Default Identifier
        """
        pass

    def test_validate_identifier_otp(self) -> None:
        """Test case for validate_identifier_otp

        Validate Identifier Otp
        """
        pass


if __name__ == '__main__':
    unittest.main()
