# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_create_profile(self) -> None:
        """Test case for create_profile

        Create Profile
        """
        pass

    def test_login(self) -> None:
        """Test case for login

        Login
        """
        pass

    def test_validate_identifier(self) -> None:
        """Test case for validate_identifier

        Validate Identifier
        """
        pass

    def test_verify_identifier(self) -> None:
        """Test case for verify_identifier

        Verify Identifier
        """
        pass


if __name__ == '__main__':
    unittest.main()
