# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.flow_response_base import FlowResponseBase

class TestFlowResponseBase(unittest.TestCase):
    """FlowResponseBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FlowResponseBase:
        """Test FlowResponseBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FlowResponseBase`
        """
        model = FlowResponseBase()
        if include_optional:
            return FlowResponseBase(
                id = ''
            )
        else:
            return FlowResponseBase(
                id = '',
        )
        """

    def testFlowResponseBase(self):
        """Test FlowResponseBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
