# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.list_users_response import ListUsersResponse

class TestListUsersResponse(unittest.TestCase):
    """ListUsersResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListUsersResponse:
        """Test ListUsersResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListUsersResponse`
        """
        model = ListUsersResponse()
        if include_optional:
            return ListUsersResponse(
                items = [
                    identity_sdk.models.user_response.UserResponse(
                        id = '', 
                        status = 'unspecified', 
                        first_name = '', 
                        middle_name = '', 
                        last_name = '', 
                        email = '', 
                        phone_number = '', 
                        country = '', 
                        birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        must_change_password = True, )
                    ],
                pagination = identity_sdk.models.page_response.PageResponse(
                    total = 56, 
                    page = 56, 
                    size = 56, 
                    pages = 56, 
                    has_next_page = True, 
                    has_previous_page = True, )
            )
        else:
            return ListUsersResponse(
                items = [
                    identity_sdk.models.user_response.UserResponse(
                        id = '', 
                        status = 'unspecified', 
                        first_name = '', 
                        middle_name = '', 
                        last_name = '', 
                        email = '', 
                        phone_number = '', 
                        country = '', 
                        birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        must_change_password = True, )
                    ],
                pagination = identity_sdk.models.page_response.PageResponse(
                    total = 56, 
                    page = 56, 
                    size = 56, 
                    pages = 56, 
                    has_next_page = True, 
                    has_previous_page = True, ),
        )
        """

    def testListUsersResponse(self):
        """Test ListUsersResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
