# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.verify_identifier_request import VerifyIdentifierRequest

class TestVerifyIdentifierRequest(unittest.TestCase):
    """VerifyIdentifierRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyIdentifierRequest:
        """Test VerifyIdentifierRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyIdentifierRequest`
        """
        model = VerifyIdentifierRequest()
        if include_optional:
            return VerifyIdentifierRequest(
                flow_id = '',
                device_id = '',
                otp_code = ''
            )
        else:
            return VerifyIdentifierRequest(
                flow_id = '',
                device_id = '',
                otp_code = '',
        )
        """

    def testVerifyIdentifierRequest(self):
        """Test VerifyIdentifierRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
