# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.get_users_batch_request import GetUsersBatchRequest

class TestGetUsersBatchRequest(unittest.TestCase):
    """GetUsersBatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetUsersBatchRequest:
        """Test GetUsersBatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetUsersBatchRequest`
        """
        model = GetUsersBatchRequest()
        if include_optional:
            return GetUsersBatchRequest(
                user_ids = [
                    ''
                    ]
            )
        else:
            return GetUsersBatchRequest(
                user_ids = [
                    ''
                    ],
        )
        """

    def testGetUsersBatchRequest(self):
        """Test GetUsersBatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
