# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.validate_identifier_otp_request import ValidateIdentifierOTPRequest

class TestValidateIdentifierOTPRequest(unittest.TestCase):
    """ValidateIdentifierOTPRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ValidateIdentifierOTPRequest:
        """Test ValidateIdentifierOTPRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ValidateIdentifierOTPRequest`
        """
        model = ValidateIdentifierOTPRequest()
        if include_optional:
            return ValidateIdentifierOTPRequest(
                identifier_id = '',
                otp_code = 100000.0
            )
        else:
            return ValidateIdentifierOTPRequest(
                identifier_id = '',
                otp_code = 100000.0,
        )
        """

    def testValidateIdentifierOTPRequest(self):
        """Test ValidateIdentifierOTPRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
