# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.user_create_profile import UserCreateProfile

class TestUserCreateProfile(unittest.TestCase):
    """UserCreateProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCreateProfile:
        """Test UserCreateProfile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCreateProfile`
        """
        model = UserCreateProfile()
        if include_optional:
            return UserCreateProfile(
                first_name = '',
                middle_name = '',
                last_name = '',
                country = '',
                birthday = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                password = ''
            )
        else:
            return UserCreateProfile(
                first_name = '',
        )
        """

    def testUserCreateProfile(self):
        """Test UserCreateProfile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
