# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.api.sessions_api import SessionsApi


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SessionsApi()

    def tearDown(self) -> None:
        pass

    def test_delete_session(self) -> None:
        """Test case for delete_session

        Delete Session
        """
        pass

    def test_get_session(self) -> None:
        """Test case for get_session

        Get Sessions
        """
        pass

    def test_get_user_sessions(self) -> None:
        """Test case for get_user_sessions

        Get User Sessions
        """
        pass


if __name__ == '__main__':
    unittest.main()
