# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from identity_sdk.models.user_filters import UserFilters

class TestUserFilters(unittest.TestCase):
    """UserFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserFilters:
        """Test UserFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserFilters`
        """
        model = UserFilters()
        if include_optional:
            return UserFilters(
                email = '',
                first_name = '',
                last_name = '',
                country = '',
                status = 'unspecified'
            )
        else:
            return UserFilters(
        )
        """

    def testUserFilters(self):
        """Test UserFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
