# coding: utf-8

# flake8: noqa
"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from media_sdk.models.get_media_batch_request import GetMediaBatchRequest
    from media_sdk.models.get_media_batch_response import GetMediaBatchResponse
    from media_sdk.models.get_signed_url_request import GetSignedUrlRequest
    from media_sdk.models.get_signed_url_response import GetSignedUrlResponse
    from media_sdk.models.http_validation_error import HTTPValidationError
    from media_sdk.models.list_media_request import ListMediaRequest
    from media_sdk.models.list_media_response import ListMediaResponse
    from media_sdk.models.media import Media
    from media_sdk.models.media_category import MediaCategory
    from media_sdk.models.media_filters import MediaFilters
    from media_sdk.models.media_status import MediaStatus
    from media_sdk.models.media_variant import MediaVariant
    from media_sdk.models.page_request import PageRequest
    from media_sdk.models.page_response import PageResponse
    from media_sdk.models.validation_error import ValidationError
    from media_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from media_sdk.models.get_media_batch_request import GetMediaBatchRequest
from media_sdk.models.get_media_batch_response import GetMediaBatchResponse
from media_sdk.models.get_signed_url_request import GetSignedUrlRequest
from media_sdk.models.get_signed_url_response import GetSignedUrlResponse
from media_sdk.models.http_validation_error import HTTPValidationError
from media_sdk.models.list_media_request import ListMediaRequest
from media_sdk.models.list_media_response import ListMediaResponse
from media_sdk.models.media import Media
from media_sdk.models.media_category import MediaCategory
from media_sdk.models.media_filters import MediaFilters
from media_sdk.models.media_status import MediaStatus
from media_sdk.models.media_variant import MediaVariant
from media_sdk.models.page_request import PageRequest
from media_sdk.models.page_response import PageResponse
from media_sdk.models.validation_error import ValidationError
from media_sdk.models.validation_error_loc_inner import ValidationErrorLocInner

""",
            name=__name__,
            doc=__doc__,
        )
    )
