# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MediaCategory(str, Enum):
    """
    MediaCategory
    """

    """
    allowed enum values
    """
    AVATAR = 'avatar'
    COVER = 'cover'
    POST = 'post'
    BANNER = 'banner'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MediaCategory from a JSON string"""
        return cls(json.loads(json_str))


