# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.workspace_b_box_query import WorkspaceBBoxQuery

class TestWorkspaceBBoxQuery(unittest.TestCase):
    """WorkspaceBBoxQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceBBoxQuery:
        """Test WorkspaceBBoxQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceBBoxQuery`
        """
        model = WorkspaceBBoxQuery()
        if include_optional:
            return WorkspaceBBoxQuery(
                bbox = workspace_sdk.models.b_box.BBox(
                    north_east = workspace_sdk.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    south_west = workspace_sdk.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
                filters = workspace_sdk.models.workspace_b_box_filters.WorkspaceBBoxFilters(
                    status = 'draft', 
                    category_ids = [
                        56
                        ], )
            )
        else:
            return WorkspaceBBoxQuery(
                bbox = workspace_sdk.models.b_box.BBox(
                    north_east = workspace_sdk.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    south_west = workspace_sdk.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
        )
        """

    def testWorkspaceBBoxQuery(self):
        """Test WorkspaceBBoxQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
