# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.api.amenities_api import AmenitiesApi


class TestAmenitiesApi(unittest.TestCase):
    """AmenitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AmenitiesApi()

    def tearDown(self) -> None:
        pass

    def test_batch_amenities(self) -> None:
        """Test case for batch_amenities

        Batch Amenities
        """
        pass

    def test_create_amenity(self) -> None:
        """Test case for create_amenity

        Create Amenity
        """
        pass

    def test_get_amenity(self) -> None:
        """Test case for get_amenity

        Get Amenity
        """
        pass

    def test_list_amenities(self) -> None:
        """Test case for list_amenities

        List Amenities
        """
        pass

    def test_update_amenity(self) -> None:
        """Test case for update_amenity

        Update Amenity
        """
        pass


if __name__ == '__main__':
    unittest.main()
