# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.amenity_create import AmenityCreate

class TestAmenityCreate(unittest.TestCase):
    """AmenityCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmenityCreate:
        """Test AmenityCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmenityCreate`
        """
        model = AmenityCreate()
        if include_optional:
            return AmenityCreate(
                name = '',
                type = 'boolean',
                key = ''
            )
        else:
            return AmenityCreate(
                name = '',
        )
        """

    def testAmenityCreate(self):
        """Test AmenityCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
