# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.api.features_api import FeaturesApi


class TestFeaturesApi(unittest.TestCase):
    """FeaturesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeaturesApi()

    def tearDown(self) -> None:
        pass

    def test_batch(self) -> None:
        """Test case for batch

        Features Batch
        """
        pass

    def test_create_feature(self) -> None:
        """Test case for create_feature

        Create Feature
        """
        pass

    def test_delete_workspace_feature(self) -> None:
        """Test case for delete_workspace_feature

        Delete Feature
        """
        pass


if __name__ == '__main__':
    unittest.main()
