# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.api.workspaces_api import WorkspacesApi


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkspacesApi()

    def tearDown(self) -> None:
        pass

    def test_activate_amenity(self) -> None:
        """Test case for activate_amenity

        Activate Amenity
        """
        pass

    def test_activate_category(self) -> None:
        """Test case for activate_category

        Activate Category
        """
        pass

    def test_activate_feature(self) -> None:
        """Test case for activate_feature

        Activate Feature
        """
        pass

    def test_create_amenity(self) -> None:
        """Test case for create_amenity

        Create Amenity
        """
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create Category
        """
        pass

    def test_create_feature(self) -> None:
        """Test case for create_feature

        Create Feature
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create Workspace
        """
        pass

    def test_deactivate_amenity(self) -> None:
        """Test case for deactivate_amenity

        Deactivate Amenity
        """
        pass

    def test_deactivate_category(self) -> None:
        """Test case for deactivate_category

        Deactivate Category
        """
        pass

    def test_deactivate_feature(self) -> None:
        """Test case for deactivate_feature

        Deactivate Feature
        """
        pass

    def test_delete_feature(self) -> None:
        """Test case for delete_feature

        Delete Feature
        """
        pass

    def test_delete_workspace(self) -> None:
        """Test case for delete_workspace

        Delete Workspace
        """
        pass

    def test_deprecate_amenity(self) -> None:
        """Test case for deprecate_amenity

        Deprecate Amenity
        """
        pass

    def test_deprecate_category(self) -> None:
        """Test case for deprecate_category

        Deprecate Category
        """
        pass

    def test_get_amenities_batch(self) -> None:
        """Test case for get_amenities_batch

        Get Amenities Batch
        """
        pass

    def test_get_amenity(self) -> None:
        """Test case for get_amenity

        Get Amenity
        """
        pass

    def test_get_categories_batch(self) -> None:
        """Test case for get_categories_batch

        Get Categories Batch
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get Category
        """
        pass

    def test_get_features_batch(self) -> None:
        """Test case for get_features_batch

        Get Features Batch
        """
        pass

    def test_get_workspace_by_handle(self) -> None:
        """Test case for get_workspace_by_handle

        Get Workspace By Handle
        """
        pass

    def test_get_workspace_by_id(self) -> None:
        """Test case for get_workspace_by_id

        Get Workspace By Id
        """
        pass

    def test_get_workspace_features(self) -> None:
        """Test case for get_workspace_features

        Get Workspace Features
        """
        pass

    def test_get_workspaces_by_bbox(self) -> None:
        """Test case for get_workspaces_by_bbox

        Get Workspaces By Bbox
        """
        pass

    def test_list_amenities(self) -> None:
        """Test case for list_amenities

        List Amenities
        """
        pass

    def test_list_categories(self) -> None:
        """Test case for list_categories

        List Categories
        """
        pass

    def test_list_workspaces(self) -> None:
        """Test case for list_workspaces

        List Workspaces
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update Workspace
        """
        pass


if __name__ == '__main__':
    unittest.main()
