# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.api.v1_api import V1Api


class TestV1Api(unittest.TestCase):
    """V1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = V1Api()

    def tearDown(self) -> None:
        pass

    def test_activate_amenity_in_category_api_v1_categories_category_id_amenities_amenity_id_activate_put(self) -> None:
        """Test case for activate_amenity_in_category_api_v1_categories_category_id_amenities_amenity_id_activate_put

        Activate Amenity In Category
        """
        pass

    def test_activate_workspace(self) -> None:
        """Test case for activate_workspace

        Activate Workspace
        """
        pass

    def test_add_amenity_to_category(self) -> None:
        """Test case for add_amenity_to_category

        Add Amenity To Category
        """
        pass

    def test_add_amenity_to_workspace(self) -> None:
        """Test case for add_amenity_to_workspace

        Add Amenity To Workspace
        """
        pass

    def test_batch_amenities(self) -> None:
        """Test case for batch_amenities

        Batch Amenities
        """
        pass

    def test_batch_categories(self) -> None:
        """Test case for batch_categories

        Batch Categories
        """
        pass

    def test_batch_workspaces(self) -> None:
        """Test case for batch_workspaces

        Get Workspaces By Ids
        """
        pass

    def test_check_amenities_enabled(self) -> None:
        """Test case for check_amenities_enabled

        Check Amenities Enabled
        """
        pass

    def test_create_amenity(self) -> None:
        """Test case for create_amenity

        Create Amenity
        """
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create Category
        """
        pass

    def test_create_workspace(self) -> None:
        """Test case for create_workspace

        Create Workspace
        """
        pass

    def test_deactivate_amenity_in_category_api_v1_categories_category_id_amenities_amenity_id_deactivate_put(self) -> None:
        """Test case for deactivate_amenity_in_category_api_v1_categories_category_id_amenities_amenity_id_deactivate_put

        Deactivate Amenity In Category
        """
        pass

    def test_deactivate_workspace(self) -> None:
        """Test case for deactivate_workspace

        Deactivate Workspace
        """
        pass

    def test_deprecate_amenity_in_category_api_v1_categories_category_id_amenities_amenity_id_deprecate_put(self) -> None:
        """Test case for deprecate_amenity_in_category_api_v1_categories_category_id_amenities_amenity_id_deprecate_put

        Deprecate Amenity In Category
        """
        pass

    def test_get_amenity(self) -> None:
        """Test case for get_amenity

        Get Amenity
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get Category
        """
        pass

    def test_get_workspace(self) -> None:
        """Test case for get_workspace

        Get Workspace
        """
        pass

    def test_get_workspace_by_handle(self) -> None:
        """Test case for get_workspace_by_handle

        Get Workspace By Handle
        """
        pass

    def test_list_amenities(self) -> None:
        """Test case for list_amenities

        List Amenities
        """
        pass

    def test_list_amenities_in_category_api_v1_categories_category_id_amenities_get(self) -> None:
        """Test case for list_amenities_in_category_api_v1_categories_category_id_amenities_get

        List Amenities In Category
        """
        pass

    def test_list_categories(self) -> None:
        """Test case for list_categories

        List Categories
        """
        pass

    def test_remove_amenity_from_workspace(self) -> None:
        """Test case for remove_amenity_from_workspace

        Remove Amenity From Workspace
        """
        pass

    def test_suspend_workspace(self) -> None:
        """Test case for suspend_workspace

        Suspend Workspace
        """
        pass

    def test_update_amenity(self) -> None:
        """Test case for update_amenity

        Update Amenity
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update Category
        """
        pass

    def test_update_workspace(self) -> None:
        """Test case for update_workspace

        Update Workspace
        """
        pass

    def test_validate_workspace_exists(self) -> None:
        """Test case for validate_workspace_exists

        Validate Workspace Exists
        """
        pass


if __name__ == '__main__':
    unittest.main()
