# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.workspace_response import WorkspaceResponse

class TestWorkspaceResponse(unittest.TestCase):
    """WorkspaceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceResponse:
        """Test WorkspaceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceResponse`
        """
        model = WorkspaceResponse()
        if include_optional:
            return WorkspaceResponse(
                id = 56,
                type = 0,
                status = 0,
                name = '',
                handle = '',
                category_id = 56,
                avatar_id = '',
                cover_id = '',
                formatted_address = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WorkspaceResponse(
                id = 56,
                name = '',
                handle = '',
                category_id = 56,
        )
        """

    def testWorkspaceResponse(self):
        """Test WorkspaceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
