# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.workspace_filters import WorkspaceFilters

class TestWorkspaceFilters(unittest.TestCase):
    """WorkspaceFilters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceFilters:
        """Test WorkspaceFilters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceFilters`
        """
        model = WorkspaceFilters()
        if include_optional:
            return WorkspaceFilters(
                status = 'draft',
                name = '',
                created_by = '',
                created_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_before = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                google_place_id = '',
                bbox = workspace_sdk.models.b_box.BBox(
                    north_east = workspace_sdk.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), 
                    south_west = workspace_sdk.models.lat_lng.LatLng(
                        latitude = 1.337, 
                        longitude = 1.337, ), ),
                radius_m = 56,
                location = workspace_sdk.models.lat_lng.LatLng(
                    latitude = 1.337, 
                    longitude = 1.337, )
            )
        else:
            return WorkspaceFilters(
        )
        """

    def testWorkspaceFilters(self):
        """Test WorkspaceFilters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
