# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.batch_categories_request import BatchCategoriesRequest

class TestBatchCategoriesRequest(unittest.TestCase):
    """BatchCategoriesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchCategoriesRequest:
        """Test BatchCategoriesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchCategoriesRequest`
        """
        model = BatchCategoriesRequest()
        if include_optional:
            return BatchCategoriesRequest(
                ids = [
                    56
                    ]
            )
        else:
            return BatchCategoriesRequest(
                ids = [
                    56
                    ],
        )
        """

    def testBatchCategoriesRequest(self):
        """Test BatchCategoriesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
