# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.batch_features_response import BatchFeaturesResponse

class TestBatchFeaturesResponse(unittest.TestCase):
    """BatchFeaturesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchFeaturesResponse:
        """Test BatchFeaturesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchFeaturesResponse`
        """
        model = BatchFeaturesResponse()
        if include_optional:
            return BatchFeaturesResponse(
                features = {
                    'key' : [
                        workspace_sdk.models.feature_response.FeatureResponse(
                            id = '', 
                            workspace_id = 56, 
                            amenity_id = 56, 
                            status = 'pending', 
                            created_by = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ]
                    }
            )
        else:
            return BatchFeaturesResponse(
                features = {
                    'key' : [
                        workspace_sdk.models.feature_response.FeatureResponse(
                            id = '', 
                            workspace_id = 56, 
                            amenity_id = 56, 
                            status = 'pending', 
                            created_by = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ]
                    },
        )
        """

    def testBatchFeaturesResponse(self):
        """Test BatchFeaturesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
