# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.workspace_create import WorkspaceCreate

class TestWorkspaceCreate(unittest.TestCase):
    """WorkspaceCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceCreate:
        """Test WorkspaceCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceCreate`
        """
        model = WorkspaceCreate()
        if include_optional:
            return WorkspaceCreate(
                name = '',
                handle = '',
                category_id = 56,
                created_by = ''
            )
        else:
            return WorkspaceCreate(
                name = '',
                handle = '',
                category_id = 56,
        )
        """

    def testWorkspaceCreate(self):
        """Test WorkspaceCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
