# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.category_update import CategoryUpdate

class TestCategoryUpdate(unittest.TestCase):
    """CategoryUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CategoryUpdate:
        """Test CategoryUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CategoryUpdate`
        """
        model = CategoryUpdate()
        if include_optional:
            return CategoryUpdate(
                name = '',
                description = ''
            )
        else:
            return CategoryUpdate(
        )
        """

    def testCategoryUpdate(self):
        """Test CategoryUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
