# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.list_workspace_features_response import ListWorkspaceFeaturesResponse

class TestListWorkspaceFeaturesResponse(unittest.TestCase):
    """ListWorkspaceFeaturesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListWorkspaceFeaturesResponse:
        """Test ListWorkspaceFeaturesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListWorkspaceFeaturesResponse`
        """
        model = ListWorkspaceFeaturesResponse()
        if include_optional:
            return ListWorkspaceFeaturesResponse(
                items = [
                    workspace_sdk.models.feature.Feature(
                        id = '', 
                        status = 'pending', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        workspace_id = '', 
                        amenity_id = 56, )
                    ]
            )
        else:
            return ListWorkspaceFeaturesResponse(
                items = [
                    workspace_sdk.models.feature.Feature(
                        id = '', 
                        status = 'pending', 
                        created_by = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        deleted_by = '', 
                        workspace_id = '', 
                        amenity_id = 56, )
                    ],
        )
        """

    def testListWorkspaceFeaturesResponse(self):
        """Test ListWorkspaceFeaturesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
