# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.api.categories_api import CategoriesApi


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_add_amenity_to_category(self) -> None:
        """Test case for add_amenity_to_category

        Add Amenity To Category
        """
        pass

    def test_batch_categories(self) -> None:
        """Test case for batch_categories

        Batch Categories
        """
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create Category
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get Category
        """
        pass

    def test_list_amenities_in_category_categories_category_id_amenities_get(self) -> None:
        """Test case for list_amenities_in_category_categories_category_id_amenities_get

        List Amenities In Category
        """
        pass

    def test_list_categories(self) -> None:
        """Test case for list_categories

        List Categories
        """
        pass

    def test_update_amenity_in_category(self) -> None:
        """Test case for update_amenity_in_category

        Update Amenity In Category
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update Category
        """
        pass


if __name__ == '__main__':
    unittest.main()
