# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workspace_sdk.models.workspace_status_update import WorkspaceStatusUpdate

class TestWorkspaceStatusUpdate(unittest.TestCase):
    """WorkspaceStatusUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceStatusUpdate:
        """Test WorkspaceStatusUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceStatusUpdate`
        """
        model = WorkspaceStatusUpdate()
        if include_optional:
            return WorkspaceStatusUpdate(
                status = 'draft'
            )
        else:
            return WorkspaceStatusUpdate(
                status = 'draft',
        )
        """

    def testWorkspaceStatusUpdate(self):
        """Test WorkspaceStatusUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
