# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from post_sdk.models.get_post_media_batch_response import GetPostMediaBatchResponse

class TestGetPostMediaBatchResponse(unittest.TestCase):
    """GetPostMediaBatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPostMediaBatchResponse:
        """Test GetPostMediaBatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPostMediaBatchResponse`
        """
        model = GetPostMediaBatchResponse()
        if include_optional:
            return GetPostMediaBatchResponse(
                post_media = {
                    'key' : [
                        post_sdk.models.post_media.PostMedia(
                            id = '', 
                            post_id = '', 
                            created_by = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            alt_text = '', 
                            media_id = '', )
                        ]
                    }
            )
        else:
            return GetPostMediaBatchResponse(
                post_media = {
                    'key' : [
                        post_sdk.models.post_media.PostMedia(
                            id = '', 
                            post_id = '', 
                            created_by = '', 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            alt_text = '', 
                            media_id = '', )
                        ]
                    },
        )
        """

    def testGetPostMediaBatchResponse(self):
        """Test GetPostMediaBatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
