# coding: utf-8

"""
    NauticalStream(Workspace Microservice)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from post_sdk.models.create_post_media_schema import CreatePostMediaSchema

class TestCreatePostMediaSchema(unittest.TestCase):
    """CreatePostMediaSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePostMediaSchema:
        """Test CreatePostMediaSchema
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePostMediaSchema`
        """
        model = CreatePostMediaSchema()
        if include_optional:
            return CreatePostMediaSchema(
                post_id = 56,
                media_id = '',
                alt_text = ''
            )
        else:
            return CreatePostMediaSchema(
                post_id = 56,
                media_id = '',
        )
        """

    def testCreatePostMediaSchema(self):
        """Test CreatePostMediaSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
