# coding: utf-8

# flake8: noqa
"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from workspace_sdk.models.amenity_create import AmenityCreate
    from workspace_sdk.models.amenity_filters import AmenityFilters
    from workspace_sdk.models.amenity_status import AmenityStatus
    from workspace_sdk.models.amenity_type import AmenityType
    from workspace_sdk.models.amenity_update import AmenityUpdate
    from workspace_sdk.models.batch_amenities_request import BatchAmenitiesRequest
    from workspace_sdk.models.batch_amenity_check_request import BatchAmenityCheckRequest
    from workspace_sdk.models.batch_categories_request import BatchCategoriesRequest
    from workspace_sdk.models.batch_workspaces_request import BatchWorkspacesRequest
    from workspace_sdk.models.category_create import CategoryCreate
    from workspace_sdk.models.category_update import CategoryUpdate
    from workspace_sdk.models.http_validation_error import HTTPValidationError
    from workspace_sdk.models.list_amenities_request import ListAmenitiesRequest
    from workspace_sdk.models.pagination_request import PaginationRequest
    from workspace_sdk.models.validation_error import ValidationError
    from workspace_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
    from workspace_sdk.models.workspace_create import WorkspaceCreate
    from workspace_sdk.models.workspace_response import WorkspaceResponse
    from workspace_sdk.models.workspace_status import WorkspaceStatus
    from workspace_sdk.models.workspace_type import WorkspaceType
    from workspace_sdk.models.workspace_update import WorkspaceUpdate
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from workspace_sdk.models.amenity_create import AmenityCreate
from workspace_sdk.models.amenity_filters import AmenityFilters
from workspace_sdk.models.amenity_status import AmenityStatus
from workspace_sdk.models.amenity_type import AmenityType
from workspace_sdk.models.amenity_update import AmenityUpdate
from workspace_sdk.models.batch_amenities_request import BatchAmenitiesRequest
from workspace_sdk.models.batch_amenity_check_request import BatchAmenityCheckRequest
from workspace_sdk.models.batch_categories_request import BatchCategoriesRequest
from workspace_sdk.models.batch_workspaces_request import BatchWorkspacesRequest
from workspace_sdk.models.category_create import CategoryCreate
from workspace_sdk.models.category_update import CategoryUpdate
from workspace_sdk.models.http_validation_error import HTTPValidationError
from workspace_sdk.models.list_amenities_request import ListAmenitiesRequest
from workspace_sdk.models.pagination_request import PaginationRequest
from workspace_sdk.models.validation_error import ValidationError
from workspace_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
from workspace_sdk.models.workspace_create import WorkspaceCreate
from workspace_sdk.models.workspace_response import WorkspaceResponse
from workspace_sdk.models.workspace_status import WorkspaceStatus
from workspace_sdk.models.workspace_type import WorkspaceType
from workspace_sdk.models.workspace_update import WorkspaceUpdate

""",
            name=__name__,
            doc=__doc__,
        )
    )
