# coding: utf-8

# flake8: noqa
"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from workspace_sdk.models.amenity import Amenity
    from workspace_sdk.models.amenity_filters import AmenityFilters
    from workspace_sdk.models.amenity_status import AmenityStatus
    from workspace_sdk.models.amenity_type import AmenityType
    from workspace_sdk.models.b_box import BBox
    from workspace_sdk.models.category import Category
    from workspace_sdk.models.category_filters import CategoryFilters
    from workspace_sdk.models.category_status import CategoryStatus
    from workspace_sdk.models.create_amenity_request import CreateAmenityRequest
    from workspace_sdk.models.create_category_request import CreateCategoryRequest
    from workspace_sdk.models.create_feature_request import CreateFeatureRequest
    from workspace_sdk.models.create_workspace_request import CreateWorkspaceRequest
    from workspace_sdk.models.feature import Feature
    from workspace_sdk.models.feature_status import FeatureStatus
    from workspace_sdk.models.get_amenities_batch_request import GetAmenitiesBatchRequest
    from workspace_sdk.models.get_amenities_batch_response import GetAmenitiesBatchResponse
    from workspace_sdk.models.get_categories_batch_request import GetCategoriesBatchRequest
    from workspace_sdk.models.get_categories_batch_response import GetCategoriesBatchResponse
    from workspace_sdk.models.get_features_batch_request import GetFeaturesBatchRequest
    from workspace_sdk.models.get_features_batch_response import GetFeaturesBatchResponse
    from workspace_sdk.models.get_workspaces_batch_request import GetWorkspacesBatchRequest
    from workspace_sdk.models.get_workspaces_batch_response import GetWorkspacesBatchResponse
    from workspace_sdk.models.http_validation_error import HTTPValidationError
    from workspace_sdk.models.lat_lng import LatLng
    from workspace_sdk.models.list_amenities_request import ListAmenitiesRequest
    from workspace_sdk.models.list_amenities_response import ListAmenitiesResponse
    from workspace_sdk.models.list_categories_request import ListCategoriesRequest
    from workspace_sdk.models.list_categories_response import ListCategoriesResponse
    from workspace_sdk.models.list_workspace_features_response import ListWorkspaceFeaturesResponse
    from workspace_sdk.models.list_workspaces_request import ListWorkspacesRequest
    from workspace_sdk.models.list_workspaces_response import ListWorkspacesResponse
    from workspace_sdk.models.page_request import PageRequest
    from workspace_sdk.models.page_response import PageResponse
    from workspace_sdk.models.point import Point
    from workspace_sdk.models.update_workspace_request import UpdateWorkspaceRequest
    from workspace_sdk.models.validation_error import ValidationError
    from workspace_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
    from workspace_sdk.models.workspace import Workspace
    from workspace_sdk.models.workspace_b_box_filters import WorkspaceBBoxFilters
    from workspace_sdk.models.workspace_b_box_query_request import WorkspaceBBoxQueryRequest
    from workspace_sdk.models.workspace_filters import WorkspaceFilters
    from workspace_sdk.models.workspace_status import WorkspaceStatus
    from workspace_sdk.models.workspace_type import WorkspaceType
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from workspace_sdk.models.amenity import Amenity
from workspace_sdk.models.amenity_filters import AmenityFilters
from workspace_sdk.models.amenity_status import AmenityStatus
from workspace_sdk.models.amenity_type import AmenityType
from workspace_sdk.models.b_box import BBox
from workspace_sdk.models.category import Category
from workspace_sdk.models.category_filters import CategoryFilters
from workspace_sdk.models.category_status import CategoryStatus
from workspace_sdk.models.create_amenity_request import CreateAmenityRequest
from workspace_sdk.models.create_category_request import CreateCategoryRequest
from workspace_sdk.models.create_feature_request import CreateFeatureRequest
from workspace_sdk.models.create_workspace_request import CreateWorkspaceRequest
from workspace_sdk.models.feature import Feature
from workspace_sdk.models.feature_status import FeatureStatus
from workspace_sdk.models.get_amenities_batch_request import GetAmenitiesBatchRequest
from workspace_sdk.models.get_amenities_batch_response import GetAmenitiesBatchResponse
from workspace_sdk.models.get_categories_batch_request import GetCategoriesBatchRequest
from workspace_sdk.models.get_categories_batch_response import GetCategoriesBatchResponse
from workspace_sdk.models.get_features_batch_request import GetFeaturesBatchRequest
from workspace_sdk.models.get_features_batch_response import GetFeaturesBatchResponse
from workspace_sdk.models.get_workspaces_batch_request import GetWorkspacesBatchRequest
from workspace_sdk.models.get_workspaces_batch_response import GetWorkspacesBatchResponse
from workspace_sdk.models.http_validation_error import HTTPValidationError
from workspace_sdk.models.lat_lng import LatLng
from workspace_sdk.models.list_amenities_request import ListAmenitiesRequest
from workspace_sdk.models.list_amenities_response import ListAmenitiesResponse
from workspace_sdk.models.list_categories_request import ListCategoriesRequest
from workspace_sdk.models.list_categories_response import ListCategoriesResponse
from workspace_sdk.models.list_workspace_features_response import ListWorkspaceFeaturesResponse
from workspace_sdk.models.list_workspaces_request import ListWorkspacesRequest
from workspace_sdk.models.list_workspaces_response import ListWorkspacesResponse
from workspace_sdk.models.page_request import PageRequest
from workspace_sdk.models.page_response import PageResponse
from workspace_sdk.models.point import Point
from workspace_sdk.models.update_workspace_request import UpdateWorkspaceRequest
from workspace_sdk.models.validation_error import ValidationError
from workspace_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
from workspace_sdk.models.workspace import Workspace
from workspace_sdk.models.workspace_b_box_filters import WorkspaceBBoxFilters
from workspace_sdk.models.workspace_b_box_query_request import WorkspaceBBoxQueryRequest
from workspace_sdk.models.workspace_filters import WorkspaceFilters
from workspace_sdk.models.workspace_status import WorkspaceStatus
from workspace_sdk.models.workspace_type import WorkspaceType

""",
            name=__name__,
            doc=__doc__,
        )
    )
