# coding: utf-8

# flake8: noqa
"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from identity_sdk.models.authenticated_response import AuthenticatedResponse
    from identity_sdk.models.create_flow_request import CreateFlowRequest
    from identity_sdk.models.create_identifier_request import CreateIdentifierRequest
    from identity_sdk.models.create_profile_request import CreateProfileRequest
    from identity_sdk.models.flow_metadata import FlowMetadata
    from identity_sdk.models.flow_response_base import FlowResponseBase
    from identity_sdk.models.flow_step import FlowStep
    from identity_sdk.models.flow_type import FlowType
    from identity_sdk.models.get_users_batch_request import GetUsersBatchRequest
    from identity_sdk.models.get_users_batch_response import GetUsersBatchResponse
    from identity_sdk.models.http_validation_error import HTTPValidationError
    from identity_sdk.models.identifier_response import IdentifierResponse
    from identity_sdk.models.identifier_type import IdentifierType
    from identity_sdk.models.list_users_request import ListUsersRequest
    from identity_sdk.models.list_users_response import ListUsersResponse
    from identity_sdk.models.login_request import LoginRequest
    from identity_sdk.models.page_request import PageRequest
    from identity_sdk.models.page_response import PageResponse
    from identity_sdk.models.session_response import SessionResponse
    from identity_sdk.models.session_status import SessionStatus
    from identity_sdk.models.session_type import SessionType
    from identity_sdk.models.user_create_admin_request import UserCreateAdminRequest
    from identity_sdk.models.user_create_admin_response import UserCreateAdminResponse
    from identity_sdk.models.user_create_profile import UserCreateProfile
    from identity_sdk.models.user_filters import UserFilters
    from identity_sdk.models.user_response import UserResponse
    from identity_sdk.models.user_status import UserStatus
    from identity_sdk.models.user_update import UserUpdate
    from identity_sdk.models.validate_flow_request import ValidateFlowRequest
    from identity_sdk.models.validate_identifier_otp_request import ValidateIdentifierOTPRequest
    from identity_sdk.models.validate_identifier_request import ValidateIdentifierRequest
    from identity_sdk.models.validation_error import ValidationError
    from identity_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
    from identity_sdk.models.verify_identifier_request import VerifyIdentifierRequest
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from identity_sdk.models.authenticated_response import AuthenticatedResponse
from identity_sdk.models.create_flow_request import CreateFlowRequest
from identity_sdk.models.create_identifier_request import CreateIdentifierRequest
from identity_sdk.models.create_profile_request import CreateProfileRequest
from identity_sdk.models.flow_metadata import FlowMetadata
from identity_sdk.models.flow_response_base import FlowResponseBase
from identity_sdk.models.flow_step import FlowStep
from identity_sdk.models.flow_type import FlowType
from identity_sdk.models.get_users_batch_request import GetUsersBatchRequest
from identity_sdk.models.get_users_batch_response import GetUsersBatchResponse
from identity_sdk.models.http_validation_error import HTTPValidationError
from identity_sdk.models.identifier_response import IdentifierResponse
from identity_sdk.models.identifier_type import IdentifierType
from identity_sdk.models.list_users_request import ListUsersRequest
from identity_sdk.models.list_users_response import ListUsersResponse
from identity_sdk.models.login_request import LoginRequest
from identity_sdk.models.page_request import PageRequest
from identity_sdk.models.page_response import PageResponse
from identity_sdk.models.session_response import SessionResponse
from identity_sdk.models.session_status import SessionStatus
from identity_sdk.models.session_type import SessionType
from identity_sdk.models.user_create_admin_request import UserCreateAdminRequest
from identity_sdk.models.user_create_admin_response import UserCreateAdminResponse
from identity_sdk.models.user_create_profile import UserCreateProfile
from identity_sdk.models.user_filters import UserFilters
from identity_sdk.models.user_response import UserResponse
from identity_sdk.models.user_status import UserStatus
from identity_sdk.models.user_update import UserUpdate
from identity_sdk.models.validate_flow_request import ValidateFlowRequest
from identity_sdk.models.validate_identifier_otp_request import ValidateIdentifierOTPRequest
from identity_sdk.models.validate_identifier_request import ValidateIdentifierRequest
from identity_sdk.models.validation_error import ValidationError
from identity_sdk.models.validation_error_loc_inner import ValidationErrorLocInner
from identity_sdk.models.verify_identifier_request import VerifyIdentifierRequest

""",
            name=__name__,
            doc=__doc__,
        )
    )
