# coding: utf-8

"""
    NauticalStream(workspace-service)

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FlowStep(str, Enum):
    """
    FlowStep
    """

    """
    allowed enum values
    """
    UNSPECIFIED = 'unspecified'
    VALIDATE_IDENTIFIER = 'validate_identifier'
    LOGIN = 'login'
    REGISTER = 'register'
    CREATE_PROFILE = 'create_profile'
    VERIFY_IDENTIFIER = 'verify_identifier'
    PASSWORD_RESET = 'password_reset'
    SET_NEW_PASSWORD = 'set_new_password'
    COMPLETED = 'completed'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FlowStep from a JSON string"""
        return cls(json.loads(json_str))


